### ISSUE TITLE
logs overwhelmed by Failing the WebSocket connection: 1006

### ISSUE THREAD

**Issue by messense** [aaugustin/websockets#167]
Seeing this a lot in logs when closing a websocket connection.

Code `1006` seems caused by `readexactly` hitting `EOF`, which seems fine when closing websocket connection.

**Comment by RemiCardona** [comment]
could you try the patch in PR #127 ? This should reduce the severity of messages in this very case.

**Comment by JCharante** [comment]
#127 was just recently merged into master. Is your issue still occurring @messense?

**Comment by messense** [comment]
Fixed, thanks.

**Comment by messense** [comment]
Oh, still occurring

```
2017-03-29 11:33:57,429 INFO websockets.protocol.fail_connection:613   Failing the WebSocket connection: 1006
```

**Comment by JCharante** [comment]
Did you update via pip/pypi? It still has [v3.2](https://github.com/aaugustin/websockets/releases/tag/3.2), all the way from August.

I'll download the master branch and see if I can reproduce it.

**Comment by messense** [comment]
I am using the master branch.

```
pip install -U https://github.com/aaugustin/websockets/archive/master.zip
```

**Comment by JCharante** [comment]
TIL you can do that with pip.

I'm also getting a code 1006 in the server logs when I run `example/server.py` and run the following in a browser (to throw the 1006 error).

```
ws = new WebSocket('ws://0.0.0.0:8765')
ws = new WebSocket('ws://0.0.0.0:8765', 'hi')
```

**Comment by messense** [comment]
The code I am running in production is in here:

https://github.com/bosondata/chrome-prerender/blob/master/prerender/chromerdp.py#L86

**Comment by RemiCardona** [comment]
Do you have a full backtrace ? What kind of websocket server are you connecting to ?

Thanks

**Comment by aaugustin** [comment]
FWIW I released 3.3 today.

It includes the latest changes related to the issue discussed here.

Testing with that version may make it easier to confirm we're all talking about the same version of the code.

**Comment by messense** [comment]
The latest version still occurring.

@RemiCardona I am connecting to Chrome remote debugger.

**Comment by messense** [comment]
The problem is that it is always logged in here:

https://github.com/aaugustin/websockets/blob/master/websockets/protocol.py#L618

**Comment by aaugustin** [comment]
Argh, that link points to the master branch, so I can't tell what line of code you were pointing to.

Pro-tip: press `y` and GitHub will change the URL to a permalink.

**Comment by messense** [comment]
@aaugustin https://github.com/aaugustin/websockets/blob/a786635863f591106b258716be2d2998692e2505/websockets/protocol.py#L638

**Comment by aaugustin** [comment]
#172 was closed but it seemed quite reasonable — at the very least a good start.
